#!/usr/bin/env bash
set -e
echo "Running virt emulator"

ARGS=""
if [ "$1" = "debug" ]; then
  ARGS="-monitor unix:/tmp/qemu-monitor-socket,server,nowait -s -S"
fi

MSI_CAPABILITIES=""

XHCI_CAPABILITIES="$(qemu-system-aarch64 -device qemu-xhci,help)"

if echo "$XHCI_CAPABILITIES" | grep -q "msi "; then
  MSI_CAPABILITIES="msi=on,msix=off,"
fi

OS_TYPE="$(uname)"

DISPLAY_MODE="default"
SELECTED_GPU="virtio-gpu-pci"

if [[ "$OS_TYPE" = "Darwin" ]]; then
    NETDEV=" -netdev vmnet-bridged,id=net0,ifname=en0"
    PRIVILEGE="sudo"
    DISPLAY_MODE="sdl"
elif [[ -d /sys/class/net/tap0 && -d /sys/class/net/br0 ]]; then
    # TAP is a bridge
    NETDEV="-netdev tap,id=net0,ifname=tap0,script=no,downscript=no,vnet_hdr=off"
    PRIVILEGE=""
elif [[ "$OS_TYPE" = "Linux" ]]; then
    NETDEV=" -netdev user,id=net0"
    PRIVILEGE=""
fi

DUMP="-object filter-dump,id=f0,netdev=net0,file=/tmp/virtio.pcap"
echo "Using networking mode: $NETARG"
$PRIVILEGE qemu-system-aarch64 \
  -M virt \
  -cpu cortex-a72 \
  -m 512M \
  -kernel kernel.elf \
  -device $SELECTED_GPU \
  -display $DISPLAY_MODE \
  $NETDEV \
  -device virtio-net-pci,netdev=net0,mac=52:54:00:12:34:56 \
  $DUMP \
  -serial mon:stdio \
  -drive file=disk.img,if=none,format=raw,id=hd0 \
  -device virtio-blk-pci,drive=hd0 \
  -device qemu-xhci,${MSI_CAPABILITIES}id=usb \
  -device usb-kbd,bus=usb.0 \
  -d guest_errors \
  $ARGS
