#!/bin/bash

MODE="virt"
ARGS=()

for arg in "$@"; do
  case $arg in
    MODE=*) MODE="${arg#MODE=}" ;;
    *) ARGS+=("$arg") ;;
  esac
done

echo $OS_TYPE

if [[ "$(uname)" == "Darwin" ]]; then
osascript <<EOF
tell application "Terminal"
    do script "cd \"$PWD\"; ./run_$MODE debug"
    do script "cd \"$PWD\"; ./debug ${ARGS[*]}"
end tell
EOF
  exit 0
fi

if [ -r /etc/os-release ]; then
  . /etc/os-release
fi

if [ "${ID:-}" = "ubuntu" ]; then
  setsid env SERIAL_LOG=/tmp/serial.log MODE="$MODE" bash -c 'trap "" INT; exec ./run_"$MODE" debug' </dev/null >/dev/null 2>&1 &

  exec ./debug "${ARGS[@]}"
else
  (./run_$MODE debug) & (exec ./debug "${ARGS[@]}")
fi
