#!/bin/bash

MODE="raspi"
ARGS=()

for arg in "$@"; do
  case $arg in
    MODE=*) MODE="${arg#MODE=}" ;;
    *) ARGS+=("$arg") ;;
  esac
done

# Apri una nuova finestra di terminale e lancia ./run_$MODE debug
gnome-terminal -- bash -c "cd \"$PWD\"; ./run_$MODE debug; exec bash"

# Apri un'altra finestra di terminale e lancia ./debug con gli argomenti passati
gnome-terminal -- bash -c "cd \"$PWD\"; ./debug ${ARGS[*]}; exec bash"

